language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

smalltalk:
  - Pharo-6.1
  - Pharo-7.0
  - Pharo32-8.0
  - Pharo64-8.0
  - Pharo32-9.0
  - Pharo64-9.0
  
addons:
  homebrew:
    packages:
      - sqlite3
  apt:
    packages:
      - sqlite3
      - libsqlite3-0:i386
